// ==UserScript==
// @name DDO Toolbox | Adapter | Mey
// @namespace https://dutchdesignersoutlet.nl/
// @version 2.0.1
// @description Exacte Mey OrderDetail-productdata, EAN en voorraad voor de DDO Toolbox.
// @match https://www.dutchdesignersoutlet.com/admin.php?section=products*
// @grant GM_xmlhttpRequest
// @connect meyb2b.com
// @run-at document-start
// @updateURL https://raw.githubusercontent.com/CPVB86/tempermonkey/main/DDO/toolbox/adapters/ddo-adapter-mey.user.js
// @downloadURL https://raw.githubusercontent.com/CPVB86/tempermonkey/main/DDO/toolbox/adapters/ddo-adapter-mey.user.js
// ==/UserScript==
(() => {
  'use strict';
  const ID='mey', VERSION='2.0.1';
  const TABLE='#tabs-3 table.options', PID='#tabs-1 input[name="supplier_pid"]', BRAND='#tabs-1 #select2-brand-container';
  const CONTEXT={dataareaid:'ME:NO',custid:'385468',assortid:'ddd8763b-b678-4004-ba8b-c64d45b5333c',ordertypeid:'NO',webSocketUniqueId:crypto?.randomUUID?.()||`ws-${Date.now()}-${Math.floor(Math.random()*1e6)}`};
  const $=(selector,root=document)=>root.querySelector(selector), norm=value=>String(value||'').toUpperCase().replace(/\s+/g,'').replace(/\(.*?\)/g,'').trim();
  const decode=event=>{try{return JSON.parse(event.detail||'{}')}catch{return {}}};
  const send=(name,data)=>document.dispatchEvent(new CustomEvent(`ddo-toolbox:${name}`,{detail:JSON.stringify(data)}));

  function isMey(){const node=$(BRAND),selected=$('#tabs-1 select[name="brand"] option:checked'),value=(node?.getAttribute('title')||node?.textContent||selected?.textContent||'').trim().toLowerCase();if(value.includes('mey'))return true;return[...document.querySelectorAll('#tabs-1 select,#tabs-1 [role="combobox"]')].some(element=>{const option=element.tagName==='SELECT'?element.options[element.selectedIndex]:null;return String(option?.textContent||element.textContent||element.value||'').trim().toLowerCase().includes('mey')})}
  function announce(){send('adapter-state',{id:ID,label:'Mey',version:VERSION,updateUrl:'https://raw.githubusercontent.com/CPVB86/tempermonkey/main/DDO/toolbox/adapters/ddo-adapter-mey.user.js',priority:80,available:isMey(),reason:isMey()?'':'Geen Mey-merk'})}
  function status(requestId,text,kind='busy',done=false,changed=0,autoSave=false){send('adapter-status',{requestId,text,kind,done,changed,autoSave})}
  function parsePid(value){const match=String(value||'').trim().match(/^(\d+)-(\d+)$/);return match?{style:match[1],color:match[2]}:{style:'',color:''}}
  function post(endpoint,style,color){const unique=`${Date.now()}r${Math.floor(Math.random()*1000)}`,url=`https://meyb2b.com/b2bapi?-/${unique}/${endpoint}`,styleQuery={custareaid:'ME',styleareaid:'NO',styleid:String(style),variantid:'*'};if(endpoint==='AssortmentDetail/collection')styleQuery.yattrib=String(color);else styleQuery.zkey='*';const payload=[{_getparams:{'':'undefined'},_webSocketUniqueId:CONTEXT.webSocketUniqueId,_url:endpoint,_dataareaid:CONTEXT.dataareaid,_agentid:null,_custid:CONTEXT.custid,_method:'read',styles:[styleQuery],assortid:CONTEXT.assortid,ordertypeid:CONTEXT.ordertypeid}];return new Promise((resolve,reject)=>GM_xmlhttpRequest({method:'POST',url,data:JSON.stringify(payload),headers:{'content-type':'application/json;charset=UTF-8',accept:'application/json, text/plain, */*'},withCredentials:true,timeout:15000,onload:response=>{if(response.status<200||response.status>=400)return reject(Error(`Mey HTTP ${response.status}`));try{resolve(JSON.parse(response.responseText||''))}catch{reject(Error('Ongeldige Mey-data'))}},onerror:()=>reject(Error('Netwerkfout bij Mey')),ontimeout:()=>reject(Error('Timeout bij Mey'))}))}
  function qty(value){const number=Number(value)||0;return number<=0?0:number<=2?1:number===3?2:number===4?3:5}
  function exactMap(json,color,source){const raw=json?.[0]?.result||[],records=Array.isArray(raw)?raw:[raw],map=new Map(),wanted=String(color).trim();for(const record of records){const values=source==='assortment'?record?.detailData?.xvalues:record?.xvalues;for(const [key,value] of Object.entries(values||{})){const bra=String(key).match(/^([A-Z]{1,4});([^;]+);(\d{2,3})$/i),apparel=String(key).match(/^\*;([^;]+);([^;]+)$/);let size='',keyColor='';if(bra){keyColor=String(bra[2]).trim();size=norm(`${bra[3]}${bra[1]}`)}else if(apparel){keyColor=String(apparel[1]).trim();const keySize=norm(apparel[2]),valueSize=norm(value?.size||apparel[2]);if(keySize!==valueSize)continue;size=keySize}else continue;if(keyColor!==wanted||!size)continue;const ean=String(value?.ean||value?.eanCode||value?.gtin||value?.barcode||'').replace(/\D/g,''),blocked=source==='order'&&value?.blocked===true,stockValue=source==='order'?(value?.stock??value?.quantity):null,hasStock=stockValue!==null&&stockValue!==undefined&&stockValue!=='',parsedStock=hasStock?Number(stockValue):NaN,remote=blocked?0:Number.isFinite(parsedStock)?Math.max(0,parsedStock):null,entry={ean,remote,blocked,key:String(key),source},known=map.get(size);if(!known){map.set(size,entry);continue}if(known.ean&&entry.ean&&known.ean!==entry.ean)throw Error(`Conflicterende exacte ${source}-EAN voor ${size}`);if(Number.isFinite(known.remote)&&Number.isFinite(entry.remote)&&known.remote!==entry.remote)throw Error(`Conflicterende exacte ${source}-stock voor ${size}`);if(known.blocked!==entry.blocked)throw Error(`Conflicterende blocked-status voor ${size}`);map.set(size,{...known,ean:known.ean||entry.ean,remote:Number.isFinite(known.remote)?known.remote:entry.remote})}}return map}
  function pairs(order,assortment){const map=new Map();for(const [size,live] of order){const catalog=assortment.get(size);if(live.ean&&catalog?.ean&&live.ean!==catalog.ean)throw Error(`OrderDetail en AssortmentDetail EAN verschillen voor ${size}`);const ean=live.ean||catalog?.ean||'';map.set(size,{ean,stock:Number.isFinite(live.remote)?qty(live.remote):null,available:live.remote,blocked:live.blocked,key:live.key,eanSource:live.ean?'OrderDetail':ean?'AssortmentDetail':''})}console.table([...map].map(([size,value])=>({size,ean:value.ean,eanSource:value.eanSource||'geen',remoteStock:value.available??'ontbreekt',blocked:value.blocked,ddoStock:value.stock??'niet wijzigen',key:value.key})));return map}
  function input(element,value){element.value=String(value);element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}))}
  function apply(map){let changed=0;document.querySelectorAll(`${TABLE} tbody tr`).forEach(row=>{const size=norm($('td:first-child input,td:first-child select',row)?.value||$('td:first-child',row)?.textContent),entry=map.get(size),ean=$('input[name$="[barcode]"]',row),stock=$('input[name$="[stock]"]',row);if(!entry)return;let altered=false;if(ean&&entry.ean&&ean.value!==entry.ean){input(ean,entry.ean);altered=true}if(stock&&Number.isFinite(entry.stock)&&stock.value!==String(entry.stock)){input(stock,entry.stock);altered=true}if(altered)changed++});return changed}

  document.addEventListener('ddo-toolbox:discover',announce);
  document.addEventListener('ddo-toolbox:run-adapter',async event=>{const data=decode(event);if(data.id!==ID)return;const pid=parsePid($(PID)?.value);if(!pid.style||!pid.color)return status(data.requestId,'Mey Supplier PID vereist exact STYLE-KLEUR','error',true,0,data.autoSave);try{status(data.requestId,'Mey OrderDetail laden…');const order=exactMap(await post('OrderDetail/collection',pid.style,pid.color),pid.color,'order');if(!order.size)return status(data.requestId,'Geen exacte Mey-varianten voor deze kleur','error',true,0,data.autoSave);const missingEan=[...order.values()].some(entry=>!entry.ean),assortment=missingEan?exactMap(await post('AssortmentDetail/collection',pid.style,pid.color),pid.color,'assortment'):new Map(),map=pairs(order,assortment),changed=apply(map);status(data.requestId,`${changed} rijen exact gevuld`,'success',true,changed,!!data.autoSave)}catch(error){console.error('[DDO Adapter / Mey]',error);status(data.requestId,error.message||'Ophalen mislukt','error',true,0,data.autoSave)}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',announce,{once:true});else announce();
})();
