// ==UserScript==
// @name DDO Toolbox | Adapter | Mey
// @namespace https://dutchdesignersoutlet.nl/
// @version 1.2.2
// @description Mey-locaties, API-data, kleur- en maatparsing voor de DDO Toolbox.
// @match https://www.dutchdesignersoutlet.com/admin.php?section=products*
// @grant GM_xmlhttpRequest
// @connect meyb2b.com
// @run-at document-start
// @updateURL https://raw.githubusercontent.com/CPVB86/tempermonkey/main/DDO/toolbox/adapters/ddo-adapter-mey.user.js
// @downloadURL https://raw.githubusercontent.com/CPVB86/tempermonkey/main/DDO/toolbox/adapters/ddo-adapter-mey.user.js
// ==/UserScript==
(() => {
  'use strict';
  const ID='mey', VERSION='1.2.2';
  const TABLE='#tabs-3 table.options', PID='#tabs-1 input[name="supplier_pid"]', BRAND='#tabs-1 #select2-brand-container';
  const CONTEXT={dataareaid:'ME:NO',custid:'385468',assortid:'ddd8763b-b678-4004-ba8b-c64d45b5333c',ordertypeid:'NO'};
  const $=(selector,root=document)=>root.querySelector(selector), norm=value=>String(value||'').toUpperCase().replace(/\s+/g,'').replace(/\(.*?\)/g,'').trim();
  const decode=event=>{try{return JSON.parse(event.detail||'{}')}catch{return {}}};
  const send=(name,data)=>document.dispatchEvent(new CustomEvent(`ddo-toolbox:${name}`,{detail:JSON.stringify(data)}));

  function isMey(){const node=$(BRAND),selected=$('#tabs-1 select[name="brand"] option:checked'),value=(node?.getAttribute('title')||node?.textContent||selected?.textContent||'').trim().toLowerCase();if(value.includes('mey'))return true;return[...document.querySelectorAll('#tabs-1 select,#tabs-1 [role="combobox"]')].some(element=>{const option=element.tagName==='SELECT'?element.options[element.selectedIndex]:null;return String(option?.textContent||element.textContent||element.value||'').trim().toLowerCase().includes('mey')})}
  function announce(){send('adapter-state',{id:ID,label:'Mey',version:VERSION,updateUrl:'https://raw.githubusercontent.com/CPVB86/tempermonkey/main/DDO/adapters/ddo-adapter-mey.user.js',priority:80,available:isMey(),reason:isMey()?'':'Geen Mey-merk'})}
  function status(requestId,text,kind='busy',done=false,changed=0,autoSave=false){send('adapter-status',{requestId,text,kind,done,changed,autoSave})}
  function parsePid(value){const source=String(value||'').trim(),dash=source.match(/^\s*(\d+)\s*-\s*(\d+)\s*$/);if(dash)return{style:dash[1],color:dash[2]};const numbers=source.match(/\d+/g)||[];if(!numbers.length)return{style:'',color:''};const style=[...numbers].sort((a,b)=>b.length-a.length)[0]||'',colors=numbers.filter(number=>number!==style&&number.length<=6),semi=source.match(/(?:^|;)(\d{4,})(?:;|$)/)?.[1]||'';return{style:semi&&semi.length>=style.length?semi:style,color:colors.at(-1)||''}}
  function post(endpoint,style,color){const unique=`${Date.now()}r${Math.floor(Math.random()*1000)}`,socket=crypto?.randomUUID?.()||`ws-${Date.now()}-${Math.floor(Math.random()*1e6)}`,url=`https://meyb2b.com/b2bapi?-/${unique}/${endpoint}`,styleQuery={custareaid:'ME',styleareaid:'NO',styleid:String(style),variantid:'*'};if(endpoint==='AssortmentDetail/collection')styleQuery.yattrib=String(color);else styleQuery.zkey='*';const payload=[{_getparams:{'':'undefined'},_webSocketUniqueId:socket,_url:endpoint,_dataareaid:CONTEXT.dataareaid,_agentid:null,_custid:CONTEXT.custid,_method:'read',styles:[styleQuery],assortid:CONTEXT.assortid,ordertypeid:CONTEXT.ordertypeid}];return new Promise((resolve,reject)=>GM_xmlhttpRequest({method:'POST',url,data:JSON.stringify(payload),headers:{'content-type':'application/json;charset=UTF-8',accept:'application/json, text/plain, */*'},withCredentials:true,timeout:15000,onload:response=>{if(response.status<200||response.status>=400)return reject(Error(`Mey HTTP ${response.status}`));try{resolve(JSON.parse(response.responseText||''))}catch{reject(Error('Ongeldige Mey-data'))}},onerror:()=>reject(Error('Netwerkfout bij Mey')),ontimeout:()=>reject(Error('Timeout bij Mey'))}))}
  function qty(value){const number=Number(value)||0;return number<=0?0:number<=2?1:number===3?2:number===4?3:5}
  function exactMap(json,color,source){const raw=json?.[0]?.result||[],records=Array.isArray(raw)?raw:[raw],map=new Map(),conflicts=new Set(),wanted=String(color).trim();for(const record of records){const values=source==='assortment'?record?.detailData?.xvalues:record?.xvalues;for(const [key,value] of Object.entries(values||{})){const bra=String(key).match(/^([A-Z]{1,4});([^;]+);(\d{2,3})$/i),apparel=String(key).match(/^\*;([^;]+);([^;]+)$/);let size='',keyColor='';if(bra){keyColor=String(bra[2]).trim();size=norm(`${bra[3]}${bra[1]}`)}else if(apparel){keyColor=String(apparel[1]).trim();const keySize=norm(apparel[2]),valueSize=norm(value?.size||apparel[2]);if(keySize!==valueSize)continue;size=keySize}else continue;if(keyColor!==wanted||!size)continue;const ean=String(value?.ean||value?.eanCode||value?.gtin||value?.barcode||'').replace(/\D/g,''),remote=Number(value?.stock??value?.quantity??0)||0,entry={ean,remote,key:String(key),source},known=map.get(size);if(!known)map.set(size,entry);else if(known.ean&&entry.ean&&known.ean!==entry.ean){conflicts.add(size);console.error(`[DDO Adapter / Mey] Conflicterende ${source}-EAN`,size,known,entry)}else if(entry.remote>known.remote||(!known.ean&&entry.ean))map.set(size,{...entry,ean:entry.ean||known.ean})}}if(conflicts.size)throw Error(`Meerdere exacte ${source}-EAN's voor: ${[...conflicts].join(', ')}`);return map}
  function pairs(orderJson,assortmentJson,color){const order=exactMap(orderJson,color,'order'),assortment=exactMap(assortmentJson,color,'assortment'),map=new Map(),sizes=new Set([...order.keys(),...assortment.keys()]);for(const size of sizes){const live=order.get(size),catalog=assortment.get(size),ean=catalog?.ean||live?.ean||'',remote=live?Number(live.remote):null;if(catalog?.ean&&live?.ean&&catalog.ean!==live.ean)console.warn('[DDO Adapter / Mey] EAN-bronnen verschillen; AssortmentDetail gebruikt',{size,assortment:catalog.ean,order:live.ean,assortmentKey:catalog.key,orderKey:live.key});if(ean||live||catalog)map.set(size,{ean,stock:Number.isFinite(remote)?qty(remote):null,available:remote,key:catalog?.key||live?.key,stockKey:live?.key||''})}console.table([...map].map(([size,value])=>({size,ean:value.ean,remoteStock:value.available??'geen exacte match',stock:value.stock??'niet wijzigen',assortmentEAN:assortment.get(size)?.ean||'',orderEAN:order.get(size)?.ean||'',eanKey:value.key,stockKey:value.stockKey})));return map}
  function input(element,value){element.value=String(value);element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}))}
  function apply(map){let changed=0;document.querySelectorAll(`${TABLE} tbody tr`).forEach(row=>{const size=norm($('td:first-child input,td:first-child select',row)?.value||$('td:first-child',row)?.textContent),entry=map.get(size),ean=$('input[name$="[barcode]"]',row),stock=$('input[name$="[stock]"]',row);if(!entry)return;let altered=false;if(ean&&entry.ean&&ean.value!==entry.ean){input(ean,entry.ean);altered=true}if(stock&&Number.isFinite(entry.stock)&&stock.value!==String(entry.stock)){input(stock,entry.stock);altered=true}if(altered)changed++});return changed}

  document.addEventListener('ddo-toolbox:discover',announce);
  document.addEventListener('ddo-toolbox:run-adapter',async event=>{const data=decode(event);if(data.id!==ID)return;const pid=parsePid($(PID)?.value);if(!pid.style||!pid.color)return status(data.requestId,'Mey Supplier PID vereist exacte style-kleur','error',true,0,data.autoSave);try{status(data.requestId,'Mey assortiment en varianten laden…');const [order,assortment]=await Promise.all([post('OrderDetail/collection',pid.style,pid.color),post('AssortmentDetail/collection',pid.style,pid.color)]),map=pairs(order,assortment,pid.color);if(!map.size)return status(data.requestId,'Geen exacte Mey-matches voor deze kleur','error',true,0,data.autoSave);const changed=apply(map);status(data.requestId,`${changed} rijen exact gevuld`,changed?'success':'error',true,changed,!!data.autoSave)}catch(error){console.error('[DDO Adapter / Mey]',error);status(data.requestId,error.message||'Ophalen mislukt','error',true,0,data.autoSave)}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',announce,{once:true});else announce();
})();
